---
# Team 84 - Melbourne
# Brendan Pichler(bpichler@student.unimelb.edu.au) 1212335
# George Wang (wagw@student.unimelb.edu.au) 1084224
# Luchen Zhou(luczhou@student.unimelb.edu.au) 1053412
# Wei Wang(wangw16@student.unimelb.edu.au) 900889
# Yihan Wang (yihwang3@student.unimelb.edu.au) 1056614

# roles/install_couchdb/tasks/main.yml

- name: Update package lists and install dependencies
  become: yes
  apt:
    update_cache: yes
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common

- name: Import Docker GPG key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /usr/share/keyrings/docker-archive-keyring.gpg

- name: Add Docker repository
  become: yes
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- name: Update package lists again and install Docker CE
  become: yes
  apt:
    update_cache: yes
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io

- name: Add current user to the Docker group
  become: yes
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Enable and start Docker service
  become: yes
  systemd:
    name: docker
    enabled: yes
    state: started

- name: Refresh group membership for "{{ ansible_user }}"
  become: yes
  command: su - {{ ansible_user }} -c "exit"
  changed_when: false

- name: Pull CouchDB Docker image
  docker_image:
    name: couchdb:{{ couchdb_version }}
    source: pull

- name: Stop and remove existing Docker container if exists
  become: yes
  docker_container:
    name: couchdb
    state: absent

- name: Create and start CouchDB Docker container
  become: yes
  docker_container:
    name: couchdb
    image: couchdb:{{ couchdb_version }}
    state: started
    ports:
      - "9100:9100"
      - "4369:4369"
      - "5984:5984"
    env:
      COUCHDB_USER: "{{ couchdb_user }}"
      COUCHDB_PASSWORD: "{{ couchdb_password }}"
      COUCHDB_SECRET: "{{ couchdb_cookie }}"
      ERL_FLAGS: "-setcookie \"{{ couchdb_cookie }}\" -name \"couchdb@{{ ansible_default_ipv4.address }}\""
    volumes:
      - "/mnt/database:/opt/couchdb/data"
