---
- name: Create an instance
  openstack.cloud.server:
    name: "{{ item.name }}"
    auto_floating_ip: false
    availability_zone: "{{ availability_zone }}"
    flavor: "{{ instance_flavor }}"
    image: "{{ instance_image }}"
    key_name: "{{ instance_key_name }}"
    network: "{{ instance_network }}"
    security_groups: "{{ sg_names }}"
    timeout: 600
    volumes: "{{ item.volumes }}"
    state: present
    wait: true
  loop: "{{ instances }}"














