- hosts: server1
  vars_files:
    - vars/vars.yml
  gather_facts: true

  vars:
    - ansible_user: ubuntu
    - ansible_ssh_private_key_file: ../mrc.pem
    - ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

  tasks:
    - name: Ensure Docker service is running
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: yes
      become: yes

    - name: Stop and remove Docker container
      ansible.builtin.docker_container:
        name: server1
        state: absent
      become: yes

    - name: Remove Docker image
      ansible.builtin.docker_image:
        name: "{{ docker_image }}"
        state: absent
        force_source: yes
      become: yes

