---
- name: Create Docker services
  hosts: swarm_managers 
  become: true
  vars_files:
    - variables/mastodon_vars.yaml 

  tasks:
  - name: Build Docker images
    community.docker.docker_image:
      name: "{{ item.name }}"
      source: "../harvester_node/streamer"
      build:
        dockerfile: Dockerfile
      state: present
    loop: "{{ domains }}"


  - name: Create the Docker service
    community.docker.docker_compose:
      project_src: mastodon-compose.yaml
      project_name: crawler
      build: false
      scale:
        crawler_{{ item.name }}: "{{ item.num_replicas }}"
      loop: "{{ domains }}"


    

    

